language: scala
scala:
    - 2.10.4
    - 2.11.4
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
sudo: false
script: sbt ++$TRAVIS_SCALA_VERSION test doc
cache:
    directories:
        - $HOME/.ivy2
